/*
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.validation

import org.eclipse.xtext.validation.Check
import org.eclipse.xtext.validation.CheckType
import it.unibz.inf.ontouml.xtext.xcore.OntoUMLClass

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class OntoUMLValidator extends AbstractOntoUMLValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					OntoUMLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check(CheckType.NORMAL)
	def checkUltimateSortalSpecialization(OntoUMLClass c){
		if(c.isSortal && c.classHierarchy)
	}
	
}
