/**
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.formatting2;

import com.google.inject.Inject;
import it.unibz.inf.ontouml.xtext.services.OntoUMLGrammarAccess;
import it.unibz.inf.ontouml.xtext.xcore.Model;
import it.unibz.inf.ontouml.xtext.xcore.ModelElement;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class OntoUMLFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private OntoUMLGrammarAccess _ontoUMLGrammarAccess;
  
  protected void _format(final Model model, @Extension final IFormattableDocument document) {
    EList<ModelElement> _elements = model.getElements();
    for (final ModelElement modelElement : _elements) {
      document.<ModelElement>format(modelElement);
    }
  }
  
  public void format(final Object model, final IFormattableDocument document) {
    if (model instanceof XtextResource) {
      _format((XtextResource)model, document);
      return;
    } else if (model instanceof Model) {
      _format((Model)model, document);
      return;
    } else if (model instanceof EObject) {
      _format((EObject)model, document);
      return;
    } else if (model == null) {
      _format((Void)null, document);
      return;
    } else if (model != null) {
      _format(model, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(model, document).toString());
    }
  }
}
