/**
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.scoping;

import it.unibz.inf.ontouml.xtext.scoping.AbstractOntoUMLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class OntoUMLScopeProvider extends AbstractOntoUMLScopeProvider {
}
