/*
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.ui.tests;

import com.google.inject.Injector;
import it.unibz.inf.ontouml.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class OntoUMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("it.unibz.inf.ontouml.xtext.OntoUML");
	}

}
