/*
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OntoUMLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/unibz/inf/ontouml/xtext/parser/antlr/internal/InternalOntoUML.tokens");
	}
}
