/**
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.ui.contentassist;

import it.unibz.inf.ontouml.xtext.ui.contentassist.AbstractOntoUMLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class OntoUMLProposalProvider extends AbstractOntoUMLProposalProvider {
}
