/**
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext;

import it.unibz.inf.ontouml.xtext.AbstractOntoUMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class OntoUMLRuntimeModule extends AbstractOntoUMLRuntimeModule {
}
