/*
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class OntoUMLRuntimeModule extends AbstractOntoUMLRuntimeModule {
}
