/*
 * generated by Xtext 2.12.0
 */
package it.unibz.inf.ontouml.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractOntoUMLScopeProvider extends DelegatingScopeProvider {
}
