/**
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.validation;

import it.unibz.inf.ontouml.xtext.validation.AbstractOntoUMLValidator;
import it.unibz.inf.ontouml.xtext.xcore.OntoUMLClass;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class OntoUMLValidator extends AbstractOntoUMLValidator {
  @Check(CheckType.NORMAL)
  public Object checkUltimateSortalSpecialization(final OntoUMLClass c) {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'}\'"
      + "\nThe method or field classHierarchy is undefined for the type OntoUMLClass");
  }
}
