/**
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.validation;

import com.google.inject.Inject;
import it.unibz.inf.ontouml.xtext.utils.ModelUtils;
import it.unibz.inf.ontouml.xtext.validation.AbstractOntoUMLValidator;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class OntoUMLValidator extends AbstractOntoUMLValidator {
  @Inject
  @Extension
  private ModelUtils _modelUtils;
}
