/**
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.ide;

import it.unibz.inf.ontouml.xtext.ide.AbstractOntoUMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class OntoUMLIdeModule extends AbstractOntoUMLIdeModule {
}
