/**
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.unibz.inf.ontouml.xtext.OntoUMLRuntimeModule;
import it.unibz.inf.ontouml.xtext.OntoUMLStandaloneSetup;
import it.unibz.inf.ontouml.xtext.ide.OntoUMLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class OntoUMLIdeSetup extends OntoUMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    OntoUMLRuntimeModule _ontoUMLRuntimeModule = new OntoUMLRuntimeModule();
    OntoUMLIdeModule _ontoUMLIdeModule = new OntoUMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_ontoUMLRuntimeModule, _ontoUMLIdeModule));
  }
}
