/**
 * generated by Xtext 2.13.0
 */
package it.unibz.inf.ontouml.xtext.ui;

import it.unibz.inf.ontouml.xtext.ui.AbstractOntoUMLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class OntoUMLUiModule extends AbstractOntoUMLUiModule {
  public OntoUMLUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
